export default {
  accNotFound: 'accessory not found',
  beta: 'You are using a beta version of the plugin - you will experience more logging than normal',
  brand: 'Flume',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  complete: '✓ Setup complete',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devNotUpdated: 'could not be updated as',
  devRemove: 'has been removed from Homebridge',
  disabling: 'Disabling plugin',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.6',
  httpRetry: 'Unable to reach Flume, retrying in 30 seconds',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  noCreds: 'Flume username and/or password and/or client id/secret not configured',
  noDataReceived: 'No data received from request',
  noDevices: 'No devices were found in your account',
  noRefreshToken: 'No refresh token has been retrieved',
  noUserId: 'No user id has been retrieved',
  pluginNotConf: 'Plugin has not been configured',
  syncFailed: 'Sync process failed as',
  updateFail: 'could not be updated as',
  zWelcome: [
    'Please ☆ this plugin on GitHub if you\'re finding it useful!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/mpatfield',
    'Check out my other Homebridge plugins! https://github.com/mpatfield',
    'This plugin currently has a 4☆ rating on HOOBS! https://bit.ly/hb-flume-review',
    'Want to see this plugin in your own language? Let me know!',
  ],
};
